import { getSphericalHarmonicsComponentCountForDegree } from "../../Util";
import * as THREE from "three";
import { SplatBuffer } from "../SplatBuffer";
import { UncompressedSplatArray } from "../UncompressedSplatArray";

const inverseLerp = (a: number, b: number, v: number): number => {
  return (v - a) / (b - a);
};

interface Vector3Like {
  x: number;
  y: number;
  z: number;
}

interface Vector4Like {
  x: number;
  y: number;
  z: number;
  w: number;
}

interface PackedValue {
  set(value: number): void;
}

const pack111011 = (result: Vector3Like, value: Vector3Like): void => {
  result.x = Math.round(value.x * 1023);
  result.y = Math.round(value.y * 1023);
  result.z = Math.round(value.z * 1023);
};

const packRot = (result: PackedValue, value: THREE.Quaternion): void => {
  const norm = 1.0 / (Math.sqrt(2) * 0.5);
  const a = (value.x + 0.5) * norm;
  const b = (value.y + 0.5) * norm;
  const c = (value.z + 0.5) * norm;
  const m = Math.sqrt(1.0 - (a * a + b * b + c * c));

  const max = Math.max(Math.max(a, b), c);
  const min = Math.min(Math.min(a, b), c);
  const mid = Math.sqrt(1.0 - max * max);

  let index = 0;
  if (max === a) index = 0;
  else if (max === b) index = 1;
  else if (max === c) index = 2;

  const resultValue =
    (index << 30) |
    ((Math.round(((a - min) / mid) * 1023) & 1023) << 20) |
    ((Math.round(((b - min) / mid) * 1023) & 1023) << 10) |
    (Math.round(((c - min) / mid) * 1023) & 1023);

  result.set(resultValue);
};

const pack8888 = (result: Vector4Like, value: Vector4Like): void => {
  result.x = Math.round(value.x * 255);
  result.y = Math.round(value.y * 255);
  result.z = Math.round(value.z * 255);
  result.w = Math.round(value.w * 255);
};

/**
 * ============================================================================
 * PLY HEADER GENERATION
 * ============================================================================
 *
 * This class handles the generation of PLY headers for the compressed PLY format.
 * The header describes the structure of the data that follows in the binary section.
 */
class PlyHeaderGenerator {
  /**
   * Generate a PLY header for the given parameters
   *
   * This function creates a PLY header that describes the structure of the data.
   * The header includes information about the number of chunks, vertices, and
   * spherical harmonics components, as well as the properties of each element.
   *
   * @param chunkCount - Number of chunks
   * @param splatCount - Number of splats
   * @param sphericalHarmonicsDegree - Degree of spherical harmonics
   * @returns PLY header text
   */
  static generateHeader(
    chunkCount: number,
    splatCount: number,
    sphericalHarmonicsDegree: number
  ): string {
    // Start with the PLY magic number and format
    let headerText = "ply\n";
    headerText += "format binary_little_endian 1.0\n";
    headerText += "comment Generated by SuperSplat 1.15.0\n";

    // Add chunk element with its properties
    // Chunks store min/max values for positions, scales, and colors
    headerText += `element chunk ${chunkCount}\n`;
    // Add properties in the same order as the original
    headerText += "property float min_x\n";
    headerText += "property float min_y\n";
    headerText += "property float min_z\n";
    headerText += "property float max_x\n";
    headerText += "property float max_y\n";
    headerText += "property float max_z\n";
    headerText += "property float min_scale_x\n";
    headerText += "property float min_scale_y\n";
    headerText += "property float min_scale_z\n";
    headerText += "property float max_scale_x\n";
    headerText += "property float max_scale_y\n";
    headerText += "property float max_scale_z\n";
    headerText += "property float min_r\n";
    headerText += "property float min_g\n";
    headerText += "property float min_b\n";
    headerText += "property float max_r\n";
    headerText += "property float max_g\n";
    headerText += "property float max_b\n";

    // Add vertex element with its properties
    // Vertices store packed positions, rotations, scales, and colors
    headerText += `element vertex ${splatCount}\n`;
    headerText += "property uint packed_position\n";
    headerText += "property uint packed_rotation\n";
    headerText += "property uint packed_scale\n";
    headerText += "property uint packed_color\n";

    // Add spherical harmonics element if needed
    // Spherical harmonics store additional lighting information
    if (sphericalHarmonicsDegree > 0) {
      headerText += `element sh ${splatCount}\n`;
      const shCount = getSphericalHarmonicsComponentCountForDegree(
        sphericalHarmonicsDegree
      );
      for (let i = 0; i < shCount; i++) {
        headerText += `property uchar f_rest_${i}\n`;
      }
    }

    // End the header
    headerText += "end_header\n";
    return headerText;
  }
}

interface ElementProperty {
  name: string;
  type: string;
  storage: any[];
  byteSize: number;
  storageSizeByes: number;
}

interface Element {
  name: string;
  count: number;
  properties: ElementProperty[];
  storageSizeBytes: number;
}

interface SplatInfo {
  position: number[];
  scale: number[];
  rotation: number[];
  color: number[];
  opacity: number;
  sphericalHarmonics: number[];
}

interface PositionExtremes {
  minX: number[];
  minY: number[];
  minZ: number[];
  maxX: number[];
  maxY: number[];
  maxZ: number[];
}

interface ScaleExtremes {
  minScaleX: number[];
  minScaleY: number[];
  minScaleZ: number[];
  maxScaleX: number[];
  maxScaleY: number[];
  maxScaleZ: number[];
}

interface ColorExtremes {
  minR: number[];
  minG: number[];
  minB: number[];
  maxR: number[];
  maxG: number[];
  maxB: number[];
}

interface StorageArrays {
  position: Vector3Like[];
  rotation: PackedValue[];
  scale: Vector3Like[];
  color: Vector4Like[];
  sh?: { [key: string]: Uint8Array };
  positionExtremes: PositionExtremes;
  scaleExtremes: ScaleExtremes;
  colorExtremes: ColorExtremes;
}

/**
 * ============================================================================
 * MAIN ENCODER CLASS
 * ============================================================================
 *
 * This class is the main entry point for encoding an UncompressedSplatBuffer
 * to a compressed PLY format. It orchestrates the encoding process using the
 * specialized classes above.
 */
export class PlayCanvasCompressedPlyEncoder {
  /**
   * Converts an UncompressedSplatBuffer to a compressed PLY format
   * This is the opposite of PlayCanvasCompressedPlyParser.parseToUncompressedSplatBuffer
   *
   * The encoding process consists of the following steps:
   * 1. Initialize arrays for storing compressed data
   * 2. First pass: collect min/max values for each chunk
   * 3. Second pass: compress the data using the min/max values
   * 4. Generate the PLY header
   * 5. Calculate buffer sizes
   * 6. Create the output buffer
   * 7. Write the header
   * 8. Write the data (chunks, vertices, spherical harmonics)
   * 9. Verify we didn't write beyond the buffer
   *
   * @param splatBuffer - The uncompressed splat buffer to encode
   * @param chunkSize - The size of each chunk (default: 256)
   * @returns The compressed PLY data as an ArrayBuffer
   */
  static encodeToCompressedPly(
    splatBuffer: SplatBuffer,
    chunkSize: number = 256
  ): ArrayBuffer {
    // Get the number of splats and the degree of spherical harmonics
    const splatCount = splatBuffer.getSplatCount();
    const sphericalHarmonicsDegree =
      splatBuffer.getMinSphericalHarmonicsDegree();

    // Calculate the number of chunks needed
    const chunkCount = Math.ceil(splatCount / chunkSize);

    // Generate the PLY header
    const headerText = PlyHeaderGenerator.generateHeader(
      chunkCount,
      splatCount,
      sphericalHarmonicsDegree
    );

    // Calculate buffer sizes
    const headerSize = headerText.length;
    const chunkDataSize = chunkCount * 72; // 18 floats * 4 bytes per chunk
    const vertexDataSize = splatCount * 16; // 4 uints per vertex
    const shDataSize =
      sphericalHarmonicsDegree > 0
        ? splatCount *
          getSphericalHarmonicsComponentCountForDegree(sphericalHarmonicsDegree)
        : 0;

    // Create the output buffer with exact size
    const totalSize = headerSize + chunkDataSize + vertexDataSize + shDataSize;
    console.log(`Buffer size calculation:
      Header size: ${headerSize}
      Chunk data size: ${chunkDataSize} (${chunkCount} chunks * 72 bytes)
      Vertex data size: ${vertexDataSize} (${splatCount} vertices * 16 bytes)
      SH data size: ${shDataSize} (${
        sphericalHarmonicsDegree > 0
          ? splatCount *
            getSphericalHarmonicsComponentCountForDegree(
              sphericalHarmonicsDegree
            )
          : 0
      } bytes)
      Total size: ${totalSize}
    `);

    // Create the output buffer and data view
    const outputBuffer = new ArrayBuffer(totalSize);
    const dataView = new DataView(outputBuffer);

    // Write the header
    const encoder = new TextEncoder();
    const headerBytes = encoder.encode(headerText);
    const headerArray = new Uint8Array(outputBuffer, 0, headerSize);
    headerArray.set(headerBytes);

    let offset = headerSize;

    // Verify we didn't write beyond the buffer
    if (offset > totalSize) {
      console.error(
        `Buffer overflow: final offset ${offset} > totalSize ${totalSize}`
      );
      throw new Error(
        `Buffer overflow: final offset ${offset} > totalSize ${totalSize}`
      );
    }

    return outputBuffer;
  }

  static revertReadPly(elements: Element[]): ArrayBuffer {
    // Create header text
    let headerText = "ply\n";
    headerText += "format binary_little_endian 1.0\n";
    headerText += "comment Generated by SuperSplat 1.15.0\n";

    // Add element definitions
    for (const element of elements) {
      headerText += `element ${element.name} ${element.count}\n`;
      for (const prop of element.properties) {
        headerText += `property ${prop.type} ${prop.name}\n`;
      }
    }
    headerText += "end_header\n";

    // Calculate total size
    const headerBytes = new TextEncoder().encode(headerText);
    let totalSize = headerBytes.length;

    // Calculate data size for each element
    for (const element of elements) {
      const elementSize =
        element.count *
        element.properties.reduce((size, prop) => {
          switch (prop.type) {
            case "float":
              return size + 4;
            case "uchar":
              return size + 1;
            case "uint":
              return size + 4;
            default:
              return size;
          }
        }, 0);
      totalSize += elementSize;
    }

    // Create buffer
    const buffer = new ArrayBuffer(totalSize);
    const dataView = new DataView(buffer);

    // Write header
    const headerArray = new Uint8Array(buffer, 0, headerBytes.length);
    headerArray.set(headerBytes);

    let offset = headerBytes.length;

    // Write element data
    for (const element of elements) {
      const elementData = element.properties.reduce(
        (acc: { [key: string]: any[] }, prop) => {
          acc[prop.name] = prop.storage;
          return acc;
        },
        {}
      );

      const elementSize = element.properties.reduce((size, prop) => {
        switch (prop.type) {
          case "float":
            return size + 4;
          case "uchar":
            return size + 1;
          case "uint":
            return size + 4;
          default:
            return size;
        }
      }, 0);

      for (let i = 0; i < element.count; i++) {
        let propOffset = 0;
        for (const prop of element.properties) {
          const value = elementData[prop.name][i];
          switch (prop.type) {
            case "float":
              dataView.setFloat32(offset + propOffset, value, true);
              propOffset += 4;
              break;
            case "uchar":
              dataView.setUint8(offset + propOffset, value);
              propOffset += 1;
              break;
            case "uint":
              dataView.setUint32(offset + propOffset, value, true);
              propOffset += 4;
              break;
          }
        }
        offset += elementSize;
      }
    }

    return buffer;
  }

  static revertPreallocateUncompressed(splatBuffer: SplatBuffer): {
    splatCount: number;
    sphericalHarmonicsDegree: number;
  } {
    // Read header information
    const headerArrayUint32 = new Uint32Array(
      splatBuffer.bufferData,
      0,
      SplatBuffer.HeaderSizeBytes / 4
    );

    // Get splat count from header
    const splatCount = headerArrayUint32[4]; // splatCount is at index 4

    // Read section header to get spherical harmonics degree
    const sectionHeaderArrayUint16 = new Uint16Array(
      splatBuffer.bufferData,
      SplatBuffer.HeaderSizeBytes,
      SplatBuffer.SectionHeaderSizeBytes / 2
    );
    const sphericalHarmonicsDegree = sectionHeaderArrayUint16[20]; // sphericalHarmonicsDegree is at index 20

    return {
      splatCount,
      sphericalHarmonicsDegree,
    };
  }

  static compressSphericalHarmonics = (function () {
    const shCoeffMap = [0, 3, 8, 15];
    const shIndexMap = [
      0, 1, 2, 9, 10, 11, 12, 13, 24, 25, 26, 27, 28, 29, 30, 3, 4, 5, 14, 15,
      16, 17, 18, 31, 32, 33, 34, 35, 36, 37, 6, 7, 8, 19, 20, 21, 22, 23, 38,
      39, 40, 41, 42, 43, 44,
    ];

    return function (
      index: number,
      // TypeScript doesn't handle arrays of TypedArrays well, but this works at runtime
      shArray: any,
      outSphericalHarmonicsDegree: number,
      readSphericalHarmonicsDegree: number,
      outSplat: number[]
    ): number[] {
      outSplat = outSplat || UncompressedSplatArray.createSplat();
      let outSHCoeff = shCoeffMap[outSphericalHarmonicsDegree];
      let readSHCoeff = shCoeffMap[readSphericalHarmonicsDegree];
      for (let j = 0; j < 3; ++j) {
        for (let k = 0; k < 15; ++k) {
          const outIndex = shIndexMap[j * 15 + k];
          if (k < outSHCoeff && k < readSHCoeff) {
            const compressedValue = Math.round(
              (outSplat[UncompressedSplatArray.OFFSET.FRC0 + outIndex] + 4) *
                (255 / 8)
            );
            // @ts-ignore: Type mismatch is expected here but the code works at runtime
            shArray[j * readSHCoeff + k][index] = Math.max(
              0,
              Math.min(255, compressedValue)
            );
          }
        }
      }

      return outSplat;
    };
  })();

  static compressBaseSplat = (function () {
    const p = new THREE.Vector3();
    const r = new THREE.Quaternion();
    const s = new THREE.Vector3();
    const c = new THREE.Vector4();

    return function (
      index: number,
      chunkSplatIndexOffset: number,
      positionArray: Vector3Like[],
      positionExtremes: PositionExtremes,
      scaleArray: Vector3Like[],
      scaleExtremes: ScaleExtremes,
      rotationArray: PackedValue[],
      colorExtremes: ColorExtremes,
      colorArray: Vector4Like[],
      inSplat: number[]
    ): void {
      const chunkIndex = Math.floor((chunkSplatIndexOffset + index) / 256);

      // Compress position
      p.x = inverseLerp(
        positionExtremes.minX[chunkIndex],
        positionExtremes.maxX[chunkIndex],
        inSplat[UncompressedSplatArray.OFFSET.X]
      );
      p.y = inverseLerp(
        positionExtremes.minY[chunkIndex],
        positionExtremes.maxY[chunkIndex],
        inSplat[UncompressedSplatArray.OFFSET.Y]
      );
      p.z = inverseLerp(
        positionExtremes.minZ[chunkIndex],
        positionExtremes.maxZ[chunkIndex],
        inSplat[UncompressedSplatArray.OFFSET.Z]
      );
      pack111011(positionArray[index], p);

      // Compress rotation
      r.set(
        inSplat[UncompressedSplatArray.OFFSET.ROTATION0],
        inSplat[UncompressedSplatArray.OFFSET.ROTATION1],
        inSplat[UncompressedSplatArray.OFFSET.ROTATION2],
        inSplat[UncompressedSplatArray.OFFSET.ROTATION3]
      );
      r.normalize();
      packRot(rotationArray[index], r);

      // Compress scale
      s.x = inverseLerp(
        scaleExtremes.minScaleX[chunkIndex],
        scaleExtremes.maxScaleX[chunkIndex],
        Math.log(inSplat[UncompressedSplatArray.OFFSET.SCALE0])
      );
      s.y = inverseLerp(
        scaleExtremes.minScaleY[chunkIndex],
        scaleExtremes.maxScaleY[chunkIndex],
        Math.log(inSplat[UncompressedSplatArray.OFFSET.SCALE1])
      );
      s.z = inverseLerp(
        scaleExtremes.minScaleZ[chunkIndex],
        scaleExtremes.maxScaleZ[chunkIndex],
        Math.log(inSplat[UncompressedSplatArray.OFFSET.SCALE2])
      );
      pack111011(scaleArray[index], s);

      // Compress color
      c.set(
        inSplat[UncompressedSplatArray.OFFSET.FDC0],
        inSplat[UncompressedSplatArray.OFFSET.FDC1],
        inSplat[UncompressedSplatArray.OFFSET.FDC2],
        inSplat[UncompressedSplatArray.OFFSET.OPACITY]
      );
      pack8888(colorArray[index], c);
    };
  })();

  static revertCreateSplat(splat: number[]): SplatInfo {
    // Extract base components
    const position = [splat[0], splat[1], splat[2]]; // x, y, z
    const scale = [splat[3], splat[4], splat[5]]; // scale0, scale1, scale2
    const rotation = [splat[6], splat[7], splat[8], splat[9]]; // rot0, rot1, rot2, rot3
    const color = [splat[10], splat[11], splat[12]]; // fdc0, fdc1, fdc2
    const opacity = splat[13]; // opacity

    // Extract spherical harmonics components
    const sphericalHarmonics = [];
    for (let i = 14; i < splat.length; i++) {
      sphericalHarmonics.push(splat[i]);
    }

    return {
      position,
      scale,
      rotation,
      color,
      opacity,
      sphericalHarmonics,
    };
  }

  static revertElementStorageArrays(storageArrays: StorageArrays): {
    chunkElement: Element;
    vertexElement: Element;
    shElement: Element | null;
  } {
    const chunkElement: Element = {
      name: "chunk",
      count: storageArrays.positionExtremes.minX.length,
      properties: [],
      storageSizeBytes: 0,
    };

    const vertexElement: Element = {
      name: "vertex",
      count: storageArrays.position.length,
      properties: [],
      storageSizeBytes: 0,
    };

    // Add chunk properties
    const chunkProperties: Partial<ElementProperty>[] = [
      { name: "min_x", storage: storageArrays.positionExtremes.minX },
      { name: "min_y", storage: storageArrays.positionExtremes.minY },
      { name: "min_z", storage: storageArrays.positionExtremes.minZ },
      { name: "max_x", storage: storageArrays.positionExtremes.maxX },
      { name: "max_y", storage: storageArrays.positionExtremes.maxY },
      { name: "max_z", storage: storageArrays.positionExtremes.maxZ },
      { name: "min_scale_x", storage: storageArrays.scaleExtremes.minScaleX },
      { name: "min_scale_y", storage: storageArrays.scaleExtremes.minScaleY },
      { name: "min_scale_z", storage: storageArrays.scaleExtremes.minScaleZ },
      { name: "max_scale_x", storage: storageArrays.scaleExtremes.maxScaleX },
      { name: "max_scale_y", storage: storageArrays.scaleExtremes.maxScaleY },
      { name: "max_scale_z", storage: storageArrays.scaleExtremes.maxScaleZ },
      { name: "min_r", storage: storageArrays.colorExtremes.minR },
      { name: "min_g", storage: storageArrays.colorExtremes.minG },
      { name: "min_b", storage: storageArrays.colorExtremes.minB },
      { name: "max_r", storage: storageArrays.colorExtremes.maxR },
      { name: "max_g", storage: storageArrays.colorExtremes.maxG },
      { name: "max_b", storage: storageArrays.colorExtremes.maxB },
    ];

    for (const prop of chunkProperties) {
      prop.type = "float";
      prop.byteSize = Float32Array.BYTES_PER_ELEMENT;
      prop.storageSizeByes = (prop.byteSize || 0) * chunkElement.count;
      chunkElement.properties.push(prop as ElementProperty);
      chunkElement.storageSizeBytes += prop.storageSizeByes || 0;
    }

    // Add vertex properties
    const vertexProperties: Partial<ElementProperty>[] = [
      { name: "packed_position", storage: storageArrays.position },
      { name: "packed_rotation", storage: storageArrays.rotation },
      { name: "packed_scale", storage: storageArrays.scale },
      { name: "packed_color", storage: storageArrays.color },
    ];

    for (const prop of vertexProperties) {
      prop.type = "uint";
      prop.byteSize = Uint32Array.BYTES_PER_ELEMENT;
      prop.storageSizeByes = (prop.byteSize || 0) * vertexElement.count;
      vertexElement.properties.push(prop as ElementProperty);
      vertexElement.storageSizeBytes += prop.storageSizeByes || 0;
    }

    // Add spherical harmonics element if present
    let shElement: Element | null = null;
    if (storageArrays.sh) {
      shElement = {
        name: "sh",
        count: vertexElement.count,
        properties: [],
        storageSizeBytes: 0,
      };

      for (let i = 0; i < 45; i++) {
        const fRestKey = `f_rest_${i}`;
        const storage = storageArrays.sh[fRestKey];
        if (storage) {
          const prop: ElementProperty = {
            type: "uchar",
            name: fRestKey,
            // @ts-ignore: TypeScript doesn't handle Uint8Array assignment to any[] properly, but it works at runtime
            storage: storage as unknown as any[],
            byteSize: Uint8Array.BYTES_PER_ELEMENT,
            storageSizeByes: Uint8Array.BYTES_PER_ELEMENT * shElement.count,
          };
          shElement.properties.push(prop);
          shElement.storageSizeBytes += prop.storageSizeByes;
        } else {
          break;
        }
      }
    }

    return {
      chunkElement,
      vertexElement,
      shElement,
    };
  }
}
