import { getSphericalHarmonicsComponentCountForDegree } from "../../Util.js";

/**
 * ============================================================================
 * PLY HEADER GENERATION
 * ============================================================================
 *
 * This class handles the generation of PLY headers for the compressed PLY format.
 * The header describes the structure of the data that follows in the binary section.
 */
class PlyHeaderGenerator {
  /**
   * Generate a PLY header for the given parameters
   *
   * This function creates a PLY header that describes the structure of the data.
   * The header includes information about the number of chunks, vertices, and
   * spherical harmonics components, as well as the properties of each element.
   *
   * @param {number} chunkCount - Number of chunks
   * @param {number} splatCount - Number of splats
   * @param {number} sphericalHarmonicsDegree - Degree of spherical harmonics
   * @returns {string} - PLY header text
   */
  static generateHeader(chunkCount, splatCount, sphericalHarmonicsDegree) {
    // Start with the PLY magic number and format
    let headerText = "ply\n";
    headerText += "format binary_little_endian 1.0\n";
    headerText += "comment Generated by SuperSplat 1.15.0\n";

    // Add chunk element with its properties
    // Chunks store min/max values for positions, scales, and colors
    headerText += `element chunk ${chunkCount}\n`;
    // Add properties in the same order as the original
    headerText += "property float min_x\n";
    headerText += "property float min_y\n";
    headerText += "property float min_z\n";
    headerText += "property float max_x\n";
    headerText += "property float max_y\n";
    headerText += "property float max_z\n";
    headerText += "property float min_scale_x\n";
    headerText += "property float min_scale_y\n";
    headerText += "property float min_scale_z\n";
    headerText += "property float max_scale_x\n";
    headerText += "property float max_scale_y\n";
    headerText += "property float max_scale_z\n";
    headerText += "property float min_r\n";
    headerText += "property float min_g\n";
    headerText += "property float min_b\n";
    headerText += "property float max_r\n";
    headerText += "property float max_g\n";
    headerText += "property float max_b\n";

    // Add vertex element with its properties
    // Vertices store packed positions, rotations, scales, and colors
    headerText += `element vertex ${splatCount}\n`;
    headerText += "property uint packed_position\n";
    headerText += "property uint packed_rotation\n";
    headerText += "property uint packed_scale\n";
    headerText += "property uint packed_color\n";

    // Add spherical harmonics element if needed
    // Spherical harmonics store additional lighting information
    if (sphericalHarmonicsDegree > 0) {
      headerText += `element sh ${splatCount}\n`;
      const shCount = getSphericalHarmonicsComponentCountForDegree(
        sphericalHarmonicsDegree
      );
      for (let i = 0; i < shCount; i++) {
        headerText += `property uchar f_rest_${i}\n`;
      }
    }

    // End the header
    headerText += "end_header\n";
    return headerText;
  }
}

/**
 * ============================================================================
 * MAIN ENCODER CLASS
 * ============================================================================
 *
 * This class is the main entry point for encoding an UncompressedSplatBuffer
 * to a compressed PLY format. It orchestrates the encoding process using the
 * specialized classes above.
 */
export class PlayCanvasCompressedPlyEncoder {
  /**
   * Converts an UncompressedSplatBuffer to a compressed PLY format
   * This is the opposite of PlayCanvasCompressedPlyParser.parseToUncompressedSplatBuffer
   *
   * The encoding process consists of the following steps:
   * 1. Initialize arrays for storing compressed data
   * 2. First pass: collect min/max values for each chunk
   * 3. Second pass: compress the data using the min/max values
   * 4. Generate the PLY header
   * 5. Calculate buffer sizes
   * 6. Create the output buffer
   * 7. Write the header
   * 8. Write the data (chunks, vertices, spherical harmonics)
   * 9. Verify we didn't write beyond the buffer
   *
   * @param {SplatBuffer} splatBuffer - The uncompressed splat buffer to encode
   * @param {number} chunkSize - The size of each chunk (default: 256)
   * @returns {ArrayBuffer} - The compressed PLY data as an ArrayBuffer
   */
  static encodeToCompressedPly(splatBuffer, chunkSize = 256) {
    // Get the number of splats and the degree of spherical harmonics
    const splatCount = splatBuffer.getSplatCount();
    const sphericalHarmonicsDegree =
      splatBuffer.getMinSphericalHarmonicsDegree();

    // Calculate the number of chunks needed
    const chunkCount = Math.ceil(splatCount / chunkSize);

    // Generate the PLY header
    const headerText = PlyHeaderGenerator.generateHeader(
      chunkCount,
      splatCount,
      sphericalHarmonicsDegree
    );

    // Calculate buffer sizes
    const headerSize = headerText.length;
    const chunkDataSize = chunkCount * 72; // 18 floats * 4 bytes per chunk
    const vertexDataSize = splatCount * 16; // 4 uints per vertex
    const shDataSize =
      sphericalHarmonicsDegree > 0
        ? splatCount *
          getSphericalHarmonicsComponentCountForDegree(sphericalHarmonicsDegree)
        : 0;

    // Create the output buffer with exact size
    const totalSize = headerSize + chunkDataSize + vertexDataSize + shDataSize;
    console.log(`Buffer size calculation:
      Header size: ${headerSize}
      Chunk data size: ${chunkDataSize} (${chunkCount} chunks * 72 bytes)
      Vertex data size: ${vertexDataSize} (${splatCount} vertices * 16 bytes)
      SH data size: ${shDataSize} (${
        sphericalHarmonicsDegree > 0
          ? splatCount *
            getSphericalHarmonicsComponentCountForDegree(
              sphericalHarmonicsDegree
            )
          : 0
      } bytes)
      Total size: ${totalSize}
    `);

    // Create the output buffer and data view
    const outputBuffer = new ArrayBuffer(totalSize);
    // const dataView = new DataView(outputBuffer);

    // Write the header
    const encoder = new TextEncoder();
    const headerBytes = encoder.encode(headerText);
    const headerArray = new Uint8Array(outputBuffer, 0, headerSize);
    headerArray.set(headerBytes);

    // Write the data
    let offset = headerSize;
    // Verify we didn't write beyond the buffer
    if (offset > totalSize) {
      console.error(
        `Buffer overflow: final offset ${offset} > totalSize ${totalSize}`
      );
      throw new Error(
        `Buffer overflow: final offset ${offset} > totalSize ${totalSize}`
      );
    }

    return outputBuffer;
  }
}
